def feature_value_map(feature_name, value, dataset_name):
    """
    Maps integer values back to categorical text for specific datasets.
    """
    if dataset_name == 'german_credit':
        mappings = {
            'checking_status': {
                1: '<0', 2: '0<=X<200', 3: 'no checking', 4: '>=200'
            },
            'credit_history': {
                1: 'critical/other existing credit', 2: 'existing paid', 3: 'delayed previously', 4: 'no credits/all paid', 5: 'all paid'
            },
            'purpose': {
                1: 'radio/tv', 2: 'education', 3: 'furniture/equipment', 4: 'new car', 5: 'used car', 6: 'business', 7: 'domestic appliance', 8: 'repairs', 9: 'other', 10: 'retraining'
            },
            'savings_status': {
                1: 'no known savings', 2: '<100', 3: '500<=X<1000', 4: '>=1000', 5: '100<=X<500'
            },
            'employment': {
                1: '>=7', 2: '1<=X<4', 3: '4<=X<7', 4: 'unemployed', 5: '<1'
            },
            'personal_status': {
                1: 'male single', 2: 'female div/dep/mar', 3: 'male div/sep', 4: 'male mar/wid'
            },
            'other_parties': {
                1: 'none', 2: 'guarantor', 3: 'co applicant'
            },
            'property_magnitude': {
                1: 'real estate', 2: 'life insurance', 3: 'no known property', 4: 'car'
            },
            'other_payment_plans': {
                1: 'none', 2: 'bank', 3: 'stores'
            },
            'housing': {
                1: 'own', 2: 'for free', 3: 'rent'
            },
            'job': {
                1: 'skilled', 2: 'unskilled resident', 3: 'high qualif/self emp/mgmt', 4: 'unemp/unskilled non res'
            },
            'own_telephone': {
                1: 'yes', 2: 'none'
            },
            'foreign_worker': {
                1: 'yes', 2: 'no'
            }
        }
        
        if feature_name in mappings:
            # Handle potential float inputs that are actually integers
            try:
                val_int = int(value)
                # Check if float is close enough to int to be considered same
                if abs(value - val_int) < 1e-5:
                    if val_int in mappings[feature_name]:
                        return mappings[feature_name][val_int]
            except (ValueError, TypeError):
                pass
    elif dataset_name == 'income':
        mappings = {
                'workclass': {
                1: 'Private',
                2: 'Self-emp-not-inc',
                3: 'Local-gov',
                4: 'Federal-gov',
                5: 'State-gov',
                6: 'Self-emp-inc'
                },
                'education': {
                1: 'Preschool',
                2: '1st-4th',
                3: '5th-6th',
                4: '7th-8th',
                5: '9th',
                6: '10th',
                7: '11th',
                8: '12th',
                9: 'HS-grad',
                10: 'Some-college',
                11: 'Assoc-voc',
                12: 'Assoc-acdm',
                13: 'Bachelors',
                14: 'Masters',
                15: 'Prof-school',
                16: 'Doctorate'
                },
                'marital-status': {
                1: 'Divorced',
                2: 'Married-civ-spouse',
                3: 'Never-married',
                4: 'Widowed',
                5: 'Married-spouse-absent',
                6: 'Separated'
                },
                'occupation': {
                1: 'Handlers-cleaners',
                2: 'Other-service',
                3: 'Sales',
                4: 'Prof-specialty',
                5: 'Tech-support',
                6: 'Adm-clerical',
                7: 'Protective-serv',
                8: 'Priv-house-serv',
                9: 'Craft-repair',
                10: 'Farming-fishing',
                11: 'Transport-moving',
                12: 'Exec-managerial',
                13: 'Machine-op-inspct',
                14: 'Armed-Forces'
                },
                'relationship': {
                1: 'Not-in-family',
                2: 'Other-relative',
                3: 'Own-child',
                4: 'Husband',
                5: 'Wife',
                6: 'Unmarried'
                },
                'race': {
                1: 'White',
                2: 'Black',
                3: 'Asian-Pac-Islander',
                4: 'Other',
                5: 'Amer-Indian-Eskimo'
                },
                'sex': {
                1: 'Male', 
                2: 'Female'
                },
                'native-country': {
                1: 'United-States',
                2: 'Mexico',
                3: 'England',
                4: 'Iran',
                5: 'Greece',
                6: 'Italy',
                7: 'Canada',
                8: 'Guatemala',
                9: 'Peru',
                10: 'South',
                11: 'Germany',
                12: 'Ecuador',
                13: 'China',
                14: 'El-Salvador',
                15: 'Philippines',
                16: 'Poland',
                17: 'Nicaragua',
                18: 'Japan',
                19: 'Puerto-Rico',
                20: 'Ireland',
                21: 'Cuba',
                22: 'Trinadad&Tobago',
                23: 'Haiti',
                24: 'India',
                25: 'Taiwan',
                26: 'Laos',
                27: 'Thailand',
                28: 'Vietnam',
                29: 'Columbia'
                }
        }
        if feature_name in mappings:
            # Handle potential float inputs that are actually integers
            try:
                val_int = int(value)
                # Check if float is close enough to int to be considered same
                if abs(value - val_int) < 1e-5:
                    if val_int in mappings[feature_name]:
                        return mappings[feature_name][val_int]
            except (ValueError, TypeError):
                pass

    elif dataset_name == 'student':
        mappings = {
            'school': {1: 'Gabriel Pereira', 2: 'Mousinho da Silveira'},
            'sex': {1: 'Female', 2: 'Male'},
            'address': {1: 'Urban', 2: 'Rural'},
            'famsize': {1: 'Greater than 3', 2: 'Less than or equal to 3'},
            'Pstatus': {1: 'Living apart', 2: 'Living together'},
            'Mjob': {1: 'at_home', 2: 'health', 3: 'other', 4: 'services', 5: 'teacher'},
            'Fjob': {1: 'teacher', 2: 'other', 3: 'services', 4: 'health', 5: 'at_home'},
            'reason': {1: 'course preference', 2: 'other', 3: 'close to home', 4: 'school reputation'},
            'guardian': {1: 'mother', 2: 'father', 3: 'other'},
            'schoolsup': {1: 'yes', 2: 'no'},
            'famsup': {1: 'no', 2: 'yes'},
            'paid': {1: 'no', 2: 'yes'},
            'activities': {1: 'no', 2: 'yes'},
            'nursery': {1: 'yes', 2: 'no'},
            'higher': {1: 'yes', 2: 'no'},
            'internet': {1: 'no', 2: 'yes'},
            'romantic': {1: 'no', 2: 'yes'},
            'Medu':{0: 'none', 1: 'primary education (4th grade)', 2: '5th to 9th grade', 3: 'secondary education', 4: 'higher education'},
            'Fedu':{0: 'none', 1: 'primary education (4th grade)', 2: '5th to 9th grade', 3: 'secondary education', 4: 'higher education'},
            'traveltime':{1: '<15 min.', 2: '15 to 30 min.', 3: '30 min. to 1 hour', 4: '>1 hour'},
            'studytime':{1: '<2 hours', 2: '2 to 5 hours', 3: '5 to 10 hours', 4: '>10 hours'},
        }
        if feature_name in mappings:
            # Handle potential float inputs that are actually integers
            try:
                val_int = int(value)
                # Check if float is close enough to int to be considered same
                if abs(value - val_int) < 1e-5:
                    if val_int in mappings[feature_name]:
                        return mappings[feature_name][val_int]
            except (ValueError, TypeError):
                pass

    elif dataset_name == 'fraud':
        mappings = {
            'employment_type': {1: 'salaried', 2: 'self-employed', 3: 'unemployed'},
            'repayment_method': {1: 'e-wallet', 2: 'bank transfer', 3: 'cash agent'},
            'mobile_os': {1: 'Android', 2: 'iOS'},
            'marketing_campaign_id': {1: 'C6', 2: 'C1', 3: 'C3', 4: 'C4', 5: 'C2', 6: 'C5'}
        }
        if feature_name in mappings:
            # Handle potential float inputs that are actually integers
            try:
                val_int = int(value)
                # Check if float is close enough to int to be considered same
                if abs(value - val_int) < 1e-5:
                    if val_int in mappings[feature_name]:
                        return mappings[feature_name][val_int]
            except (ValueError, TypeError):
                pass
    
    elif dataset_name == 'wine':
        mappings = {
            'color': {1:'red', 2: 'white'}}
        if feature_name in mappings:
            # Handle potential float inputs that are actually integers
            try:
                val_int = int(value)
                # Check if float is close enough to int to be considered same
                if abs(value - val_int) < 1e-5:
                    if val_int in mappings[feature_name]:
                        return mappings[feature_name][val_int]
            except (ValueError, TypeError):
                pass

    elif dataset_name == 'pet':
        mappings = {
            'State': {41336: 'Johor',
                41325: 'Kedah',
                41367: 'Kelantan',
                41401: 'Kuala Lumpur',
                41415: 'Labuan',
                41324: 'Melaka',
                41332: 'Negeri Sembilan',
                41335: 'Pahang',
                41330: 'Perak',
                41380: 'Perlis',
                41327: 'Pulau Pinang',
                41345: 'Sabah',
                41342: 'Sarawak',
                41326: 'Selangor',
                41361: 'Terengganu'},
            'Color1':{1: 'Black',
                2: 'Brown',
                3: 'Golden',
                4: 'Yellow',
                5: 'Cream',
                6: 'Gray',
                7: 'White'},
            'Color2':{1: 'Black',
                2: 'Brown',
                3: 'Golden',
                4: 'Yellow',
                5: 'Cream',
                6: 'Gray',
                7: 'White'},
            'Color3':{1: 'Black',
                2: 'Brown',
                3: 'Golden',
                4: 'Yellow',
                5: 'Cream',
                6: 'Gray',
                7: 'White'},
            'Type':{1: 'Dog', 2: 'Cat'},
            'Breed1':{1: 'Affenpinscher',
                2: 'Afghan Hound',
                3: 'Airedale Terrier',
                4: 'Akbash',
                5: 'Akita',
                6: 'Alaskan Malamute',
                7: 'American Bulldog',
                8: 'American Eskimo Dog',
                9: 'American Hairless Terrier',
                10: 'American Staffordshire Terrier',
                11: 'American Water Spaniel',
                12: 'Anatolian Shepherd',
                13: 'Appenzell Mountain Dog',
                14: 'Australian Cattle Dog/Blue Heeler',
                15: 'Australian Kelpie',
                16: 'Australian Shepherd',
                17: 'Australian Terrier',
                18: 'Basenji',
                19: 'Basset Hound',
                20: 'Beagle',
                21: 'Bearded Collie',
                22: 'Beauceron',
                23: 'Bedlington Terrier',
                24: 'Belgian Shepherd Dog Sheepdog',
                25: 'Belgian Shepherd Laekenois',
                26: 'Belgian Shepherd Malinois',
                27: 'Belgian Shepherd Tervuren',
                28: 'Bernese Mountain Dog',
                29: 'Bichon Frise',
                30: 'Black and Tan Coonhound',
                31: 'Black Labrador Retriever',
                32: 'Black Mouth Cur',
                33: 'Black Russian Terrier',
                34: 'Bloodhound',
                35: 'Blue Lacy',
                36: 'Bluetick Coonhound',
                37: 'Boerboel',
                38: 'Bolognese',
                39: 'Border Collie',
                40: 'Border Terrier',
                41: 'Borzoi',
                42: 'Boston Terrier',
                43: 'Bouvier des Flanders',
                44: 'Boxer',
                45: 'Boykin Spaniel',
                46: 'Briard',
                47: 'Brittany Spaniel',
                48: 'Brussels Griffon',
                49: 'Bull Terrier',
                50: 'Bullmastiff',
                51: 'Cairn Terrier',
                52: 'Canaan Dog',
                53: 'Cane Corso Mastiff',
                54: 'Carolina Dog',
                55: 'Catahoula Leopard Dog',
                56: 'Cattle Dog',
                57: 'Caucasian Sheepdog (Caucasian Ovtcharka)',
                58: 'Cavalier King Charles Spaniel',
                59: 'Chesapeake Bay Retriever',
                60: 'Chihuahua',
                61: 'Chinese Crested Dog',
                62: 'Chinese Foo Dog',
                63: 'Chinook',
                64: 'Chocolate Labrador Retriever',
                65: 'Chow Chow',
                66: "Cirneco dell'Etna",
                67: 'Clumber Spaniel',
                68: 'Cockapoo',
                69: 'Cocker Spaniel',
                70: 'Collie',
                71: 'Coonhound',
                72: 'Corgi',
                73: 'Coton de Tulear',
                74: 'Curly-Coated Retriever',
                75: 'Dachshund',
                76: 'Dalmatian',
                77: 'Dandi Dinmont Terrier',
                78: 'Doberman Pinscher',
                79: 'Dogo Argentino',
                80: 'Dogue de Bordeaux',
                81: 'Dutch Shepherd',
                82: 'English Bulldog',
                83: 'English Cocker Spaniel',
                84: 'English Coonhound',
                85: 'English Pointer',
                86: 'English Setter',
                87: 'English Shepherd',
                88: 'English Springer Spaniel',
                89: 'English Toy Spaniel',
                90: 'Entlebucher',
                91: 'Eskimo Dog',
                92: 'Feist',
                93: 'Field Spaniel',
                94: 'Fila Brasileiro',
                95: 'Finnish Lapphund',
                96: 'Finnish Spitz',
                97: 'Flat-coated Retriever',
                98: 'Fox Terrier',
                99: 'Foxhound',
                100: 'French Bulldog',
                101: 'Galgo Spanish Greyhound',
                102: 'German Pinscher',
                103: 'German Shepherd Dog',
                104: 'German Shorthaired Pointer',
                105: 'German Spitz',
                106: 'German Wirehaired Pointer',
                107: 'Giant Schnauzer',
                108: 'Glen of Imaal Terrier',
                109: 'Golden Retriever',
                110: 'Gordon Setter',
                111: 'Great Dane',
                112: 'Great Pyrenees',
                113: 'Greater Swiss Mountain Dog',
                114: 'Greyhound',
                115: 'Harrier',
                116: 'Havanese',
                117: 'Hound',
                118: 'Hovawart',
                119: 'Husky',
                120: 'Ibizan Hound',
                121: 'Illyrian Sheepdog',
                122: 'Irish Setter',
                123: 'Irish Terrier',
                124: 'Irish Water Spaniel',
                125: 'Irish Wolfhound',
                126: 'Italian Greyhound',
                127: 'Italian Spinone',
                128: 'Jack Russell Terrier',
                129: 'Jack Russell Terrier (Parson Russell Terrier)',
                130: 'Japanese Chin',
                131: 'Jindo',
                132: 'Kai Dog',
                133: 'Karelian Bear Dog',
                134: 'Keeshond',
                135: 'Kerry Blue Terrier',
                136: 'Kishu',
                137: 'Klee Kai',
                138: 'Komondor',
                139: 'Kuvasz',
                140: 'Kyi Leo',
                141: 'Labrador Retriever',
                142: 'Lakeland Terrier',
                143: 'Lancashire Heeler',
                144: 'Leonberger',
                145: 'Lhasa Apso',
                146: 'Lowchen',
                147: 'Maltese',
                148: 'Manchester Terrier',
                149: 'Maremma Sheepdog',
                150: 'Mastiff',
                151: 'McNab',
                152: 'Miniature Pinscher',
                153: 'Mountain Cur',
                154: 'Mountain Dog',
                155: 'Munsterlander',
                156: 'Neapolitan Mastiff',
                157: 'New Guinea Singing Dog',
                158: 'Newfoundland Dog',
                159: 'Norfolk Terrier',
                160: 'Norwegian Buhund',
                161: 'Norwegian Elkhound',
                162: 'Norwegian Lundehund',
                163: 'Norwich Terrier',
                164: 'Nova Scotia Duck-Tolling Retriever',
                165: 'Old English Sheepdog',
                166: 'Otterhound',
                167: 'Papillon',
                168: 'Patterdale Terrier (Fell Terrier)',
                169: 'Pekingese',
                170: 'Peruvian Inca Orchid',
                171: 'Petit Basset Griffon Vendeen',
                172: 'Pharaoh Hound',
                173: 'Pit Bull Terrier',
                174: 'Plott Hound',
                175: 'Podengo Portugueso',
                176: 'Pointer',
                177: 'Polish Lowland Sheepdog',
                178: 'Pomeranian',
                179: 'Poodle',
                180: 'Portuguese Water Dog',
                181: 'Presa Canario',
                182: 'Pug',
                183: 'Puli',
                184: 'Pumi',
                185: 'Rat Terrier',
                186: 'Redbone Coonhound',
                187: 'Retriever',
                188: 'Rhodesian Ridgeback',
                189: 'Rottweiler',
                190: 'Saint Bernard',
                191: 'Saluki',
                192: 'Samoyed',
                193: 'Sarplaninac',
                194: 'Schipperke',
                195: 'Schnauzer',
                196: 'Scottish Deerhound',
                197: 'Scottish Terrier Scottie',
                198: 'Sealyham Terrier',
                199: 'Setter',
                200: 'Shar Pei',
                201: 'Sheep Dog',
                202: 'Shepherd',
                203: 'Shetland Sheepdog Sheltie',
                204: 'Shiba Inu',
                205: 'Shih Tzu',
                206: 'Siberian Husky',
                207: 'Silky Terrier',
                208: 'Skye Terrier',
                209: 'Sloughi',
                210: 'Smooth Fox Terrier',
                211: 'South Russian Ovtcharka',
                212: 'Spaniel',
                213: 'Spitz',
                214: 'Staffordshire Bull Terrier',
                215: 'Standard Poodle',
                216: 'Sussex Spaniel',
                217: 'Swedish Vallhund',
                218: 'Terrier',
                219: 'Thai Ridgeback',
                220: 'Tibetan Mastiff',
                221: 'Tibetan Spaniel',
                222: 'Tibetan Terrier',
                223: 'Tosa Inu',
                224: 'Toy Fox Terrier',
                225: 'Treeing Walker Coonhound',
                226: 'Vizsla',
                227: 'Weimaraner',
                228: 'Welsh Corgi',
                229: 'Welsh Springer Spaniel',
                230: 'Welsh Terrier',
                231: 'West Highland White Terrier Westie',
                232: 'Wheaten Terrier',
                233: 'Whippet',
                234: 'White German Shepherd',
                235: 'Wire Fox Terrier',
                236: 'Wire-haired Pointing Griffon',
                237: 'Wirehaired Terrier',
                238: 'Xoloitzcuintle/Mexican Hairless',
                239: 'Yellow Labrador Retriever',
                240: 'Yorkshire Terrier Yorkie',
                307: 'Mixed Breed',
                241: 'Abyssinian',
                242: 'American Curl',
                243: 'American Shorthair',
                244: 'American Wirehair',
                245: 'Applehead Siamese',
                246: 'Balinese',
                247: 'Bengal',
                248: 'Birman',
                249: 'Bobtail',
                250: 'Bombay',
                251: 'British Shorthair',
                252: 'Burmese',
                253: 'Burmilla',
                254: 'Calico',
                255: 'Canadian Hairless',
                256: 'Chartreux',
                257: 'Chausie',
                258: 'Chinchilla',
                259: 'Cornish Rex',
                260: 'Cymric',
                261: 'Devon Rex',
                262: 'Dilute Calico',
                263: 'Dilute Tortoiseshell',
                264: 'Domestic Long Hair',
                265: 'Domestic Medium Hair',
                266: 'Domestic Short Hair',
                267: 'Egyptian Mau',
                268: 'Exotic Shorthair',
                269: 'Extra-Toes Cat (Hemingway Polydactyl)',
                270: 'Havana',
                271: 'Himalayan',
                272: 'Japanese Bobtail',
                273: 'Javanese',
                274: 'Korat',
                275: 'LaPerm',
                276: 'Maine Coon',
                277: 'Manx',
                278: 'Munchkin',
                279: 'Nebelung',
                280: 'Norwegian Forest Cat',
                281: 'Ocicat',
                282: 'Oriental Long Hair',
                283: 'Oriental Short Hair',
                284: 'Oriental Tabby',
                285: 'Persian',
                286: 'Pixie-Bob',
                287: 'Ragamuffin',
                288: 'Ragdoll',
                289: 'Russian Blue',
                290: 'Scottish Fold',
                291: 'Selkirk Rex',
                292: 'Siamese',
                293: 'Siberian',
                294: 'Silver',
                295: 'Singapura',
                296: 'Snowshoe',
                297: 'Somali',
                298: 'Sphynx (hairless cat)',
                299: 'Tabby',
                300: 'Tiger',
                301: 'Tonkinese',
                302: 'Torbie',
                303: 'Tortoiseshell',
                304: 'Turkish Angora',
                305: 'Turkish Van',
                306: 'Tuxedo'},
            'Breed2':{1: 'Affenpinscher',
                2: 'Afghan Hound',
                3: 'Airedale Terrier',
                4: 'Akbash',
                5: 'Akita',
                6: 'Alaskan Malamute',
                7: 'American Bulldog',
                8: 'American Eskimo Dog',
                9: 'American Hairless Terrier',
                10: 'American Staffordshire Terrier',
                11: 'American Water Spaniel',
                12: 'Anatolian Shepherd',
                13: 'Appenzell Mountain Dog',
                14: 'Australian Cattle Dog/Blue Heeler',
                15: 'Australian Kelpie',
                16: 'Australian Shepherd',
                17: 'Australian Terrier',
                18: 'Basenji',
                19: 'Basset Hound',
                20: 'Beagle',
                21: 'Bearded Collie',
                22: 'Beauceron',
                23: 'Bedlington Terrier',
                24: 'Belgian Shepherd Dog Sheepdog',
                25: 'Belgian Shepherd Laekenois',
                26: 'Belgian Shepherd Malinois',
                27: 'Belgian Shepherd Tervuren',
                28: 'Bernese Mountain Dog',
                29: 'Bichon Frise',
                30: 'Black and Tan Coonhound',
                31: 'Black Labrador Retriever',
                32: 'Black Mouth Cur',
                33: 'Black Russian Terrier',
                34: 'Bloodhound',
                35: 'Blue Lacy',
                36: 'Bluetick Coonhound',
                37: 'Boerboel',
                38: 'Bolognese',
                39: 'Border Collie',
                40: 'Border Terrier',
                41: 'Borzoi',
                42: 'Boston Terrier',
                43: 'Bouvier des Flanders',
                44: 'Boxer',
                45: 'Boykin Spaniel',
                46: 'Briard',
                47: 'Brittany Spaniel',
                48: 'Brussels Griffon',
                49: 'Bull Terrier',
                50: 'Bullmastiff',
                51: 'Cairn Terrier',
                52: 'Canaan Dog',
                53: 'Cane Corso Mastiff',
                54: 'Carolina Dog',
                55: 'Catahoula Leopard Dog',
                56: 'Cattle Dog',
                57: 'Caucasian Sheepdog (Caucasian Ovtcharka)',
                58: 'Cavalier King Charles Spaniel',
                59: 'Chesapeake Bay Retriever',
                60: 'Chihuahua',
                61: 'Chinese Crested Dog',
                62: 'Chinese Foo Dog',
                63: 'Chinook',
                64: 'Chocolate Labrador Retriever',
                65: 'Chow Chow',
                66: "Cirneco dell'Etna",
                67: 'Clumber Spaniel',
                68: 'Cockapoo',
                69: 'Cocker Spaniel',
                70: 'Collie',
                71: 'Coonhound',
                72: 'Corgi',
                73: 'Coton de Tulear',
                74: 'Curly-Coated Retriever',
                75: 'Dachshund',
                76: 'Dalmatian',
                77: 'Dandi Dinmont Terrier',
                78: 'Doberman Pinscher',
                79: 'Dogo Argentino',
                80: 'Dogue de Bordeaux',
                81: 'Dutch Shepherd',
                82: 'English Bulldog',
                83: 'English Cocker Spaniel',
                84: 'English Coonhound',
                85: 'English Pointer',
                86: 'English Setter',
                87: 'English Shepherd',
                88: 'English Springer Spaniel',
                89: 'English Toy Spaniel',
                90: 'Entlebucher',
                91: 'Eskimo Dog',
                92: 'Feist',
                93: 'Field Spaniel',
                94: 'Fila Brasileiro',
                95: 'Finnish Lapphund',
                96: 'Finnish Spitz',
                97: 'Flat-coated Retriever',
                98: 'Fox Terrier',
                99: 'Foxhound',
                100: 'French Bulldog',
                101: 'Galgo Spanish Greyhound',
                102: 'German Pinscher',
                103: 'German Shepherd Dog',
                104: 'German Shorthaired Pointer',
                105: 'German Spitz',
                106: 'German Wirehaired Pointer',
                107: 'Giant Schnauzer',
                108: 'Glen of Imaal Terrier',
                109: 'Golden Retriever',
                110: 'Gordon Setter',
                111: 'Great Dane',
                112: 'Great Pyrenees',
                113: 'Greater Swiss Mountain Dog',
                114: 'Greyhound',
                115: 'Harrier',
                116: 'Havanese',
                117: 'Hound',
                118: 'Hovawart',
                119: 'Husky',
                120: 'Ibizan Hound',
                121: 'Illyrian Sheepdog',
                122: 'Irish Setter',
                123: 'Irish Terrier',
                124: 'Irish Water Spaniel',
                125: 'Irish Wolfhound',
                126: 'Italian Greyhound',
                127: 'Italian Spinone',
                128: 'Jack Russell Terrier',
                129: 'Jack Russell Terrier (Parson Russell Terrier)',
                130: 'Japanese Chin',
                131: 'Jindo',
                132: 'Kai Dog',
                133: 'Karelian Bear Dog',
                134: 'Keeshond',
                135: 'Kerry Blue Terrier',
                136: 'Kishu',
                137: 'Klee Kai',
                138: 'Komondor',
                139: 'Kuvasz',
                140: 'Kyi Leo',
                141: 'Labrador Retriever',
                142: 'Lakeland Terrier',
                143: 'Lancashire Heeler',
                144: 'Leonberger',
                145: 'Lhasa Apso',
                146: 'Lowchen',
                147: 'Maltese',
                148: 'Manchester Terrier',
                149: 'Maremma Sheepdog',
                150: 'Mastiff',
                151: 'McNab',
                152: 'Miniature Pinscher',
                153: 'Mountain Cur',
                154: 'Mountain Dog',
                155: 'Munsterlander',
                156: 'Neapolitan Mastiff',
                157: 'New Guinea Singing Dog',
                158: 'Newfoundland Dog',
                159: 'Norfolk Terrier',
                160: 'Norwegian Buhund',
                161: 'Norwegian Elkhound',
                162: 'Norwegian Lundehund',
                163: 'Norwich Terrier',
                164: 'Nova Scotia Duck-Tolling Retriever',
                165: 'Old English Sheepdog',
                166: 'Otterhound',
                167: 'Papillon',
                168: 'Patterdale Terrier (Fell Terrier)',
                169: 'Pekingese',
                170: 'Peruvian Inca Orchid',
                171: 'Petit Basset Griffon Vendeen',
                172: 'Pharaoh Hound',
                173: 'Pit Bull Terrier',
                174: 'Plott Hound',
                175: 'Podengo Portugueso',
                176: 'Pointer',
                177: 'Polish Lowland Sheepdog',
                178: 'Pomeranian',
                179: 'Poodle',
                180: 'Portuguese Water Dog',
                181: 'Presa Canario',
                182: 'Pug',
                183: 'Puli',
                184: 'Pumi',
                185: 'Rat Terrier',
                186: 'Redbone Coonhound',
                187: 'Retriever',
                188: 'Rhodesian Ridgeback',
                189: 'Rottweiler',
                190: 'Saint Bernard',
                191: 'Saluki',
                192: 'Samoyed',
                193: 'Sarplaninac',
                194: 'Schipperke',
                195: 'Schnauzer',
                196: 'Scottish Deerhound',
                197: 'Scottish Terrier Scottie',
                198: 'Sealyham Terrier',
                199: 'Setter',
                200: 'Shar Pei',
                201: 'Sheep Dog',
                202: 'Shepherd',
                203: 'Shetland Sheepdog Sheltie',
                204: 'Shiba Inu',
                205: 'Shih Tzu',
                206: 'Siberian Husky',
                207: 'Silky Terrier',
                208: 'Skye Terrier',
                209: 'Sloughi',
                210: 'Smooth Fox Terrier',
                211: 'South Russian Ovtcharka',
                212: 'Spaniel',
                213: 'Spitz',
                214: 'Staffordshire Bull Terrier',
                215: 'Standard Poodle',
                216: 'Sussex Spaniel',
                217: 'Swedish Vallhund',
                218: 'Terrier',
                219: 'Thai Ridgeback',
                220: 'Tibetan Mastiff',
                221: 'Tibetan Spaniel',
                222: 'Tibetan Terrier',
                223: 'Tosa Inu',
                224: 'Toy Fox Terrier',
                225: 'Treeing Walker Coonhound',
                226: 'Vizsla',
                227: 'Weimaraner',
                228: 'Welsh Corgi',
                229: 'Welsh Springer Spaniel',
                230: 'Welsh Terrier',
                231: 'West Highland White Terrier Westie',
                232: 'Wheaten Terrier',
                233: 'Whippet',
                234: 'White German Shepherd',
                235: 'Wire Fox Terrier',
                236: 'Wire-haired Pointing Griffon',
                237: 'Wirehaired Terrier',
                238: 'Xoloitzcuintle/Mexican Hairless',
                239: 'Yellow Labrador Retriever',
                240: 'Yorkshire Terrier Yorkie',
                307: 'Mixed Breed',
                241: 'Abyssinian',
                242: 'American Curl',
                243: 'American Shorthair',
                244: 'American Wirehair',
                245: 'Applehead Siamese',
                246: 'Balinese',
                247: 'Bengal',
                248: 'Birman',
                249: 'Bobtail',
                250: 'Bombay',
                251: 'British Shorthair',
                252: 'Burmese',
                253: 'Burmilla',
                254: 'Calico',
                255: 'Canadian Hairless',
                256: 'Chartreux',
                257: 'Chausie',
                258: 'Chinchilla',
                259: 'Cornish Rex',
                260: 'Cymric',
                261: 'Devon Rex',
                262: 'Dilute Calico',
                263: 'Dilute Tortoiseshell',
                264: 'Domestic Long Hair',
                265: 'Domestic Medium Hair',
                266: 'Domestic Short Hair',
                267: 'Egyptian Mau',
                268: 'Exotic Shorthair',
                269: 'Extra-Toes Cat (Hemingway Polydactyl)',
                270: 'Havana',
                271: 'Himalayan',
                272: 'Japanese Bobtail',
                273: 'Javanese',
                274: 'Korat',
                275: 'LaPerm',
                276: 'Maine Coon',
                277: 'Manx',
                278: 'Munchkin',
                279: 'Nebelung',
                280: 'Norwegian Forest Cat',
                281: 'Ocicat',
                282: 'Oriental Long Hair',
                283: 'Oriental Short Hair',
                284: 'Oriental Tabby',
                285: 'Persian',
                286: 'Pixie-Bob',
                287: 'Ragamuffin',
                288: 'Ragdoll',
                289: 'Russian Blue',
                290: 'Scottish Fold',
                291: 'Selkirk Rex',
                292: 'Siamese',
                293: 'Siberian',
                294: 'Silver',
                295: 'Singapura',
                296: 'Snowshoe',
                297: 'Somali',
                298: 'Sphynx (hairless cat)',
                299: 'Tabby',
                300: 'Tiger',
                301: 'Tonkinese',
                302: 'Torbie',
                303: 'Tortoiseshell',
                304: 'Turkish Angora',
                305: 'Turkish Van',
                306: 'Tuxedo'},
            'Gender':{
                1: 'Male',
                2: 'Female'
            },
            'MaturitySize':{
                1: 'small',
                2: 'medium',
                3: 'large',
                4: 'extra large',
                0: 'not specified',
            },
            'FurLength':{
                1: 'short',
                2: 'medium',
                3: 'long',
                0: 'not specified',
            },
            'Health':{
                1: 'healthy',
                2: 'minor injury',
                3: 'serious injury',
                0: 'not specified',
            },
            'Vaccinated':{
                1: 'yes',
                2: 'no',
                0: 'not sure',
            },
            'Sterilized':{
                1: 'yes',
                2: 'no',
                0: 'not sure',
            },
            'Dewormed':{
                1: 'yes',
                2: 'no',
                0: 'not sure',
            },
            }
        if feature_name in mappings:
            # Handle potential float inputs that are actually integers
            try:
                val_int = int(value)
                # Check if float is close enough to int to be considered same
                if abs(value - val_int) < 1e-5:
                    if val_int in mappings[feature_name]:
                        return mappings[feature_name][val_int]
            except (ValueError, TypeError):
                pass
            
    elif dataset_name == 'nursery':
        mappings = {
            'parents': {
                1: 'usual', 
                2: 'pretentious', 
                3: 'great pretentious'
            },
            'has_nurs': {
                1: 'proper', 
                2: 'less proper', 
                3: 'improper', 
                4: 'critical', 
                5: 'very critical'
            },
            'children':{
                1:"1",
                2:"2",
                3:"3",
                4:"more than 3"
            },
            'form': {
                1: 'complete', 
                2: 'incomplete', 
                3: 'foster'
            },
            'housing': {
                1: 'convenient', 
                2: 'less convenient', 
                3: 'critical'
            },
            'finance': {
                1: 'convenient', 
                2: 'inconvenient'
            },
            'social': {
                1: 'non-problematic', 
                2: 'slightly problematic', 
                3: 'problematic'
            },
            'health': {
                1: 'recommended', 
                2: 'priority', 
                3: 'not recommended'
            }
        }
        if feature_name in mappings:
            # Handle potential float inputs that are actually integers
            try:
                val_int = int(value)
                # Check if float is close enough to int to be considered same
                if abs(value - val_int) < 1e-5:
                    if val_int in mappings[feature_name]:
                        return mappings[feature_name][val_int]
            except (ValueError, TypeError):
                pass
                
    return value
